# Generated by Django 3.2.15 on 2022-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221019_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='problem',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='How Can We Help You '),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='address'),
        ),
    ]
