# Generated by Django 3.2.14 on 2022-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20221025_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='problem',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='How Can We Help You?'),
        ),
    ]
