# Generated by Django 3.2.14 on 2022-10-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address'),
        ),
    ]
