# Generated by Django 3.2.15 on 2022-10-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20221031_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.staff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='accured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.staff'),
        ),
    ]
