# Generated by Django 3.2.15 on 2022-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20221031_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default='avathar.svg', null=True, upload_to='', verbose_name='Profile Pic'),
        ),
        migrations.AddField(
            model_name='staff',
            name='documents',
            field=models.FileField(null=True, upload_to='', verbose_name='upload your certificates(PDF) '),
        ),
    ]
