# Generated by Django 3.2.14 on 2022-11-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20221109_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accurorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated',
            field=models.PositiveSmallIntegerField(choices=[(1, '1- Very Bad'), (2, '1- Bad'), (3, '1- Ok'), (4, '1- Good'), (5, '1- Very Good')]),
        ),
    ]
